#
# Local scratch storage for node-bound services
# These areas may be preserved between pod restarts, but there is no such guarantee
#
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-50
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-51
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-52
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-53
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-54
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-55
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-56
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-57
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-58
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-59
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
