#
# Local persistent storage for node-bound services
#
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-persistent-60
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-persistent-61
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-persistent-62
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-persistent-63
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-persistent-64
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-persistent-65
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-persistent-66
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-persistent-67
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-persistent-68
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-persistent-69
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
