#
# Local scratch storage for node-bound services
# These areas may be preserved between pod restarts, but there is no such guarantee
#
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-30
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-31
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-32
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-33
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-34
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-35
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-36
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-37
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-38
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-scratch-39
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
# Important to bind ASAP, as any PersistentStorage is available to everyone until bound
volumeBindingMode: Immediate
