apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bcache-1-ucsd-meta
  namespace: cms-admin
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-persistent-1
  local:
    path: /xcache-meta
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          -  bcache-1.t2.ucsd.edu
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bcache-1-ucsd-meta
  namespace: cms-admin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-persistent-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bcache-1-ucsd-root
  namespace: cms-admin
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-persistent-2
  local:
    path: /xcache-root
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          -  bcache-1.t2.ucsd.edu
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bcache-1-ucsd-root
  namespace: cms-admin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-persistent-2
