apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bcache-1-ucsd-s2
  namespace: cms-admin
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-scratch-2
  local:
    path: /a/2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          -  bcache-1.t2.ucsd.edu
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bcache-1-ucsd-s2
  namespace: cms-admin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-scratch-2
