apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dtn-gpu2-kreonet-net-persistent-1
  namespace: osg
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-persistent-1
  local:
    path: /data/disk1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - pv-dtn-gpu2-kreonet-net-persistent-1
---
#
# Initially assigned to prp-osg-head
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dtn-gpu2-kreonet-net-persistent-1
  namespace: osg
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-persistent-1
