apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-esnet-xcache-01-t2-ucsd-edu-persistent-1
  namespace: cms-admin
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-persistent-1
  local:
    path: /DATA/cacheData
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - esnet-xcache-01.t2.ucsd.edu
---
#
# Initially assigned to prp-osg-collector
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-esnet-xcache-01-t2-ucsd-edu-persistent-1
  namespace: cms-admin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-persistent-1
