apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-osg-sunnyvale-stashcache.nrp.internet2.edu-1
  namespace: osg-services
spec:
  capacity:
    storage: 13Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-persistent-1
  local:
    path: /tank1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          -  osg-sunnyvale-stashcache.nrp.internet2.edu
---
#
# Initially assigned to	prp-stashcache-sunnyvale
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-osg-sunnyvale-stashcache.nrp.internet2.edu-1
  namespace: osg-services
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 13Gi
  storageClassName: local-persistent-1
