apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-osg-houston-stashcache.nrp.internet2.edu-2
  namespace: osg
spec:
  capacity:
    storage: 13Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-persistent-2
  local:
    path: /tank2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          -  osg-houston-stashcache.nrp.internet2.edu
---
#
# Initially assigned to prp-stashcache-houston
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-osg-houston-stashcache.nrp.internet2.edu-2
  namespace: osg
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 13Gi
  storageClassName: local-persistent-2
