apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-xcache11-t2-ucsd-edu-persistent-3
  namespace: osg
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-persistent-3
  local:
    path: /data12/area3
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - xcache-11.t2.ucsd.edu
---
#
# Initially assigned to prp-osg-head
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-xcache11-t2-ucsd-edu-persistent-3
  namespace: osg
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-persistent-3
